CREATE TABLE `brand_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`brandName` varchar(255) NOT NULL,
	`brandUrl` text,
	`category` text,
	`archetype` varchar(64),
	`emotionalPromise` text,
	`visualLanguage` json,
	`audienceTribe` text,
	`culturalTension` text,
	`barthesMyth` text,
	`brandType` varchar(128),
	`campaignType` enum('Heritage/Luxury','Trend-First','Long-Term Ambassador','Product Launch'),
	`weightAlpha` float,
	`weightBeta` float,
	`weightGamma` float,
	`weightPriority` text,
	`aiSummary` text,
	`rawAiResponse` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `brand_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `creator_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`handle` varchar(255) NOT NULL,
	`platform` enum('TikTok','Instagram','YouTube','Multi') NOT NULL,
	`profileUrl` text,
	`displayName` text,
	`archetype` varchar(64),
	`recurringThemes` json,
	`toneRegister` text,
	`parasocialBondStrength` float,
	`audienceRelationshipType` enum('Friend','Mentor','Authority'),
	`barthesMyth` text,
	`culturalCapital` enum('Produce','Relay'),
	`goffmanStageConsistency` enum('Consistent','Minor Gap','Significant Gap'),
	`driftSignal` enum('Zero Change','Minor Drift','Significant Drift','Full Pivot'),
	`stuartHallDecoding` enum('Dominant','Negotiated','Oppositional'),
	`nicheTopicNode` text,
	`undergroundDensity` boolean,
	`mainstreamBleed` boolean,
	`remixRate` boolean,
	`brandSaturation` boolean,
	`rogersAdopterStage` enum('Innovators','Early Adopters','Early Majority','Late Majority','Laggards'),
	`creatorNichePosition` enum('Ahead','Consistent','Behind'),
	`lifecyclePhase` enum('Emergence','Growth','Maturity','Decline'),
	`barthesNicheMeaning` text,
	`turnerLiminalPhase` enum('Pre-Liminal','Liminal','Post-Liminal Reintegration'),
	`aiSummary` text,
	`rawAiResponse` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `creator_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `match_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`creatorProfileId` int NOT NULL,
	`brandProfileId` int NOT NULL,
	`alignmentScoreRaw` float,
	`pulseScoreRaw` float,
	`stabilityScoreRaw` float,
	`archetypeMatchScore` float,
	`mythAlignmentScore` float,
	`tribMatchScore` float,
	`decodingModifier` float,
	`rogersBaseScore` float,
	`liminalAdjustment` float,
	`goffmanScore` float,
	`driftScore` float,
	`weightAlpha` float,
	`weightBeta` float,
	`weightGamma` float,
	`fitScore` float,
	`fitStatus` enum('Green Light','Proceed with Caution','Do Not Proceed'),
	`radarWarnings` json,
	`narrativeSummary` text,
	`alignmentNotes` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `match_records_id` PRIMARY KEY(`id`)
);
